#!/usr/bin/env bash
# RemoteJuggler Shell Completion Generator
# Generates shell completions for bash, zsh, and fish

set -euo pipefail

BINARY="remote-juggler"

# Commands and subcommands
COMMANDS="list detect switch validate status config token gpg debug"
CONFIG_SUBCOMMANDS="show add remove import export sync init"
TOKEN_SUBCOMMANDS="set get delete verify list"
GPG_SUBCOMMANDS="list set verify sign"

generate_bash() {
    cat << 'EOF'
# Bash completion for remote-juggler
# Generated by scripts/generate-completions.sh

_remote_juggler() {
    local cur prev words cword
    _init_completion || return

    local commands="list detect switch validate status config token gpg debug"
    local config_subcmds="show add remove import export sync init"
    local token_subcmds="set get delete verify list"
    local gpg_subcmds="list set verify sign"
    local global_opts="--help --version --verbose --mode --config"

    case "${prev}" in
        remote-juggler)
            COMPREPLY=( $(compgen -W "${commands} ${global_opts}" -- "${cur}") )
            return
            ;;
        config)
            COMPREPLY=( $(compgen -W "${config_subcmds}" -- "${cur}") )
            return
            ;;
        token)
            COMPREPLY=( $(compgen -W "${token_subcmds}" -- "${cur}") )
            return
            ;;
        gpg)
            COMPREPLY=( $(compgen -W "${gpg_subcmds}" -- "${cur}") )
            return
            ;;
        switch|validate|set|get|delete)
            # Complete with identity names from config
            local identities
            identities=$(remote-juggler list --names-only 2>/dev/null || echo "")
            COMPREPLY=( $(compgen -W "${identities}" -- "${cur}") )
            return
            ;;
        --mode)
            COMPREPLY=( $(compgen -W "cli mcp acp" -- "${cur}") )
            return
            ;;
        --config)
            _filedir
            return
            ;;
    esac

    if [[ "${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "${global_opts}" -- "${cur}") )
    else
        COMPREPLY=( $(compgen -W "${commands}" -- "${cur}") )
    fi
}

complete -F _remote_juggler remote-juggler
EOF
}

generate_zsh() {
    cat << 'EOF'
#compdef remote-juggler

# Zsh completion for remote-juggler
# Generated by scripts/generate-completions.sh

_remote_juggler() {
    local -a commands
    local -a config_subcmds
    local -a token_subcmds
    local -a gpg_subcmds

    commands=(
        'list:List all configured identities'
        'detect:Detect identity for current repository'
        'switch:Switch to a different identity'
        'validate:Validate identity connectivity'
        'status:Show current identity status'
        'config:Manage configuration'
        'token:Manage API tokens'
        'gpg:Manage GPG signing'
        'debug:Debug and diagnostics'
    )

    config_subcmds=(
        'show:Show current configuration'
        'add:Add a new identity'
        'remove:Remove an identity'
        'import:Import from SSH config'
        'export:Export configuration'
        'sync:Sync managed blocks'
        'init:Initialize configuration'
    )

    token_subcmds=(
        'set:Store a token in keychain'
        'get:Retrieve a token'
        'delete:Remove a token'
        'verify:Verify token validity'
        'list:List stored tokens'
    )

    gpg_subcmds=(
        'list:List available GPG keys'
        'set:Set signing key for identity'
        'verify:Verify GPG configuration'
        'sign:Test signing'
    )

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '(-v --version)'{-v,--version}'[Show version]' \
        '--verbose[Enable verbose output]' \
        '--mode=[Server mode]:mode:(cli mcp acp)' \
        '--config=[Config file path]:file:_files' \
        '1: :->command' \
        '*:: :->args'

    case $state in
        command)
            _describe -t commands 'remote-juggler commands' commands
            ;;
        args)
            case $words[1] in
                config)
                    _describe -t config_subcmds 'config subcommands' config_subcmds
                    ;;
                token)
                    _describe -t token_subcmds 'token subcommands' token_subcmds
                    ;;
                gpg)
                    _describe -t gpg_subcmds 'gpg subcommands' gpg_subcmds
                    ;;
                switch|validate)
                    local -a identities
                    identities=(${(f)"$(remote-juggler list --names-only 2>/dev/null)"})
                    _describe -t identities 'identities' identities
                    ;;
            esac
            ;;
    esac
}

_remote_juggler "$@"
EOF
}

generate_fish() {
    cat << 'EOF'
# Fish completion for remote-juggler
# Generated by scripts/generate-completions.sh

# Disable file completion by default
complete -c remote-juggler -f

# Global options
complete -c remote-juggler -s h -l help -d 'Show help message'
complete -c remote-juggler -s v -l version -d 'Show version'
complete -c remote-juggler -l verbose -d 'Enable verbose output'
complete -c remote-juggler -l mode -xa 'cli mcp acp' -d 'Server mode'
complete -c remote-juggler -l config -rF -d 'Config file path'

# Commands
complete -c remote-juggler -n __fish_use_subcommand -a list -d 'List all configured identities'
complete -c remote-juggler -n __fish_use_subcommand -a detect -d 'Detect identity for current repository'
complete -c remote-juggler -n __fish_use_subcommand -a switch -d 'Switch to a different identity'
complete -c remote-juggler -n __fish_use_subcommand -a validate -d 'Validate identity connectivity'
complete -c remote-juggler -n __fish_use_subcommand -a status -d 'Show current identity status'
complete -c remote-juggler -n __fish_use_subcommand -a config -d 'Manage configuration'
complete -c remote-juggler -n __fish_use_subcommand -a token -d 'Manage API tokens'
complete -c remote-juggler -n __fish_use_subcommand -a gpg -d 'Manage GPG signing'
complete -c remote-juggler -n __fish_use_subcommand -a debug -d 'Debug and diagnostics'

# Config subcommands
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a show -d 'Show current configuration'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a add -d 'Add a new identity'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a remove -d 'Remove an identity'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a import -d 'Import from SSH config'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a export -d 'Export configuration'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a sync -d 'Sync managed blocks'
complete -c remote-juggler -n '__fish_seen_subcommand_from config' -a init -d 'Initialize configuration'

# Token subcommands
complete -c remote-juggler -n '__fish_seen_subcommand_from token' -a set -d 'Store a token in keychain'
complete -c remote-juggler -n '__fish_seen_subcommand_from token' -a get -d 'Retrieve a token'
complete -c remote-juggler -n '__fish_seen_subcommand_from token' -a delete -d 'Remove a token'
complete -c remote-juggler -n '__fish_seen_subcommand_from token' -a verify -d 'Verify token validity'
complete -c remote-juggler -n '__fish_seen_subcommand_from token' -a list -d 'List stored tokens'

# GPG subcommands
complete -c remote-juggler -n '__fish_seen_subcommand_from gpg' -a list -d 'List available GPG keys'
complete -c remote-juggler -n '__fish_seen_subcommand_from gpg' -a set -d 'Set signing key for identity'
complete -c remote-juggler -n '__fish_seen_subcommand_from gpg' -a verify -d 'Verify GPG configuration'
complete -c remote-juggler -n '__fish_seen_subcommand_from gpg' -a sign -d 'Test signing'

# Identity completion for switch/validate commands
function __remote_juggler_identities
    remote-juggler list --names-only 2>/dev/null
end

complete -c remote-juggler -n '__fish_seen_subcommand_from switch' -xa '(__remote_juggler_identities)'
complete -c remote-juggler -n '__fish_seen_subcommand_from validate' -xa '(__remote_juggler_identities)'
complete -c remote-juggler -n '__fish_seen_subcommand_from token; and __fish_seen_subcommand_from set get delete' -xa '(__remote_juggler_identities)'
EOF
}

# Main
case "${1:-bash}" in
    bash)
        generate_bash
        ;;
    zsh)
        generate_zsh
        ;;
    fish)
        generate_fish
        ;;
    *)
        echo "Usage: $0 [bash|zsh|fish]" >&2
        exit 1
        ;;
esac
