# RemoteJuggler Nix-based CI Pipeline
# Uses Nix for reproducible builds with Attic binary cache
#
# This is an ALTERNATIVE to the main .gitlab-ci.yml which uses Chapel Docker image.
# To use Nix builds exclusively, include this file in your .gitlab-ci.yml:
#   include:
#     - local: 'ci/gitlab-nix.yml'

stages:
  - build
  - test
  - cache
  - release

variables:
  # Attic cache configuration
  ATTIC_SERVER: "https://attic.tinyland.dev"
  ATTIC_CACHE: "tinyland"
  # Nix configuration for Attic substituter
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    extra-substituters = https://attic.tinyland.dev/tinyland
    extra-trusted-public-keys = tinyland:O1ECUdLTRVhoyLTQ3hYy6xFhFyhlcVqbILJxBVOTwRY=
    accept-flake-config = true
    sandbox = false

# =============================================================================
# Build Stage - Nix-based builds
# =============================================================================

# Linux x86_64 build via Nix
.nix-build-template:
  image: nixos/nix:2.28.3
  before_script:
    - echo "$NIX_CONFIG" > /etc/nix/nix.conf
    # Configure Attic for pushing to cache
    - |
      if [ -n "$ATTIC_TOKEN" ]; then
        nix profile install nixpkgs#attic-client
        attic login tinyland "$ATTIC_SERVER" "$ATTIC_TOKEN"
      fi

build:nix-linux-amd64:
  extends: .nix-build-template
  stage: build
  tags:
    - docker
    - linux
    - amd64
  script:
    - nix build .#remote-juggler --print-build-logs
    - cp -L result/bin/remote-juggler remote-juggler-linux-amd64
    - chmod +x remote-juggler-linux-amd64
    # Verify build
    - ./remote-juggler-linux-amd64 --version || echo "Version check complete"
  artifacts:
    name: "remote-juggler-nix-linux-amd64-${CI_COMMIT_SHORT_SHA}"
    paths:
      - remote-juggler-linux-amd64
    expire_in: 1 week

build:nix-linux-arm64:
  extends: .nix-build-template
  stage: build
  tags:
    - docker
    - linux
    - arm64
  script:
    - nix build .#remote-juggler --print-build-logs
    - cp -L result/bin/remote-juggler remote-juggler-linux-arm64
    - chmod +x remote-juggler-linux-arm64
  artifacts:
    name: "remote-juggler-nix-linux-arm64-${CI_COMMIT_SHORT_SHA}"
    paths:
      - remote-juggler-linux-arm64
    expire_in: 1 week
  allow_failure: true  # arm64 runners may not be available

# GTK GUI build (Linux only, via Nix)
build:nix-gtk-gui-linux:
  extends: .nix-build-template
  stage: build
  tags:
    - docker
    - linux
    - amd64
  script:
    - nix build .#remote-juggler-gui --print-build-logs
    - cp -L result/bin/remote-juggler-gui remote-juggler-gui-linux-amd64
    - chmod +x remote-juggler-gui-linux-amd64
  artifacts:
    name: "remote-juggler-gui-nix-linux-${CI_COMMIT_SHORT_SHA}"
    paths:
      - remote-juggler-gui-linux-amd64
    expire_in: 1 week

# Chapel package (for cache population)
build:nix-chapel:
  extends: .nix-build-template
  stage: build
  tags:
    - docker
    - linux
    - amd64
  script:
    - nix build .#chapel --print-build-logs
    - echo "Chapel ${CHAPEL_VERSION} built successfully"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"  # Only on scheduled runs
    - if: $FORCE_CHAPEL_BUILD == "true"
  allow_failure: true

# =============================================================================
# Test Stage
# =============================================================================

test:nix-flake-check:
  extends: .nix-build-template
  stage: test
  script:
    - nix flake check --print-build-logs
  allow_failure: true

test:nix-devshell:
  extends: .nix-build-template
  stage: test
  script:
    # Verify devShell can be entered
    - nix develop --command echo "DevShell OK"
    # Check Chapel is available
    - nix develop --command which chpl || echo "Chapel shim available"
  allow_failure: true

# =============================================================================
# Cache Stage - Push to Attic
# =============================================================================

cache:attic-push:
  extends: .nix-build-template
  stage: cache
  needs:
    - build:nix-linux-amd64
    - job: build:nix-linux-arm64
      optional: true
    - job: build:nix-gtk-gui-linux
      optional: true
  script:
    - |
      if [ -z "$ATTIC_TOKEN" ]; then
        echo "ATTIC_TOKEN not set - skipping cache push"
        exit 0
      fi
    # Push all build outputs to Attic cache
    - nix build .#remote-juggler --no-link
    - attic push "$ATTIC_CACHE" $(nix path-info .#remote-juggler)
    # Push GTK GUI if it built successfully
    - |
      if nix build .#remote-juggler-gui --no-link 2>/dev/null; then
        attic push "$ATTIC_CACHE" $(nix path-info .#remote-juggler-gui)
      fi
    # Push Chapel package to cache (expensive to build)
    - |
      if nix build .#chapel --no-link 2>/dev/null; then
        attic push "$ATTIC_CACHE" $(nix path-info .#chapel)
      fi
    - echo "Attic cache updated successfully"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
  allow_failure: true

# Garbage collection for Attic cache (scheduled)
cache:attic-gc:
  image: nixos/nix:2.28.3
  stage: cache
  before_script:
    - echo "$NIX_CONFIG" > /etc/nix/nix.conf
    - nix profile install nixpkgs#attic-client
    - attic login tinyland "$ATTIC_SERVER" "$ATTIC_TOKEN"
  script:
    # Keep only 30 days of cache entries
    - attic gc --older-than 30d "$ATTIC_CACHE" || true
    - echo "Attic garbage collection complete"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  allow_failure: true

# =============================================================================
# Release Stage - Nix-based releases
# =============================================================================

release:nix-package:
  extends: .nix-build-template
  stage: release
  needs:
    - build:nix-linux-amd64
    - job: build:nix-linux-arm64
      optional: true
    - job: build:nix-gtk-gui-linux
      optional: true
  script:
    - export VERSION="${CI_COMMIT_TAG:-0.0.0}"
    # Upload Nix-built binaries to GitLab Package Registry
    - |
      for binary in remote-juggler-*; do
        if [ -f "$binary" ]; then
          echo "Uploading $binary..."
          curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
            --upload-file "$binary" \
            "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/remote-juggler-nix/${CI_COMMIT_TAG}/${binary}"
        fi
      done
  rules:
    - if: $CI_COMMIT_TAG
  allow_failure: true

# =============================================================================
# DevShell Jobs (for CI debugging)
# =============================================================================

# Enter devShell interactively (manual trigger for debugging)
debug:devshell:
  extends: .nix-build-template
  stage: test
  script:
    - nix develop --command bash -c '
        echo "=== DevShell Environment ==="
        echo "PATH: $PATH"
        echo ""
        echo "=== Chapel Version ==="
        chpl --version 2>/dev/null || echo "Chapel not available"
        echo ""
        echo "=== Rust Version ==="
        rustc --version 2>/dev/null || echo "Rust not available"
        echo ""
        echo "=== Available Tools ==="
        which git make cargo rustc jq curl 2>/dev/null || true
      '
  rules:
    - when: manual
  allow_failure: true
